<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>31403bb6-491e-4446-8a2c-a82dc04ce953</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.73.0.4073" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SqlCodes\SeedData\" />
    <Folder Include="SqlCodes\Schema\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="efpt.config.json.user" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\DTOs\" />
    <Folder Include="Models\Services\" />
    <Folder Include="StaticFiles\images\NewFolder\" />
  </ItemGroup>

</Project>
