// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class BodyRecord
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public double Weight { get; set; }

    public decimal? BodyFat { get; set; }

    public decimal? SkeletalMuscle { get; set; }

    public decimal? WaistCircumference { get; set; }

    public DateTime CreateAt { get; set; }

    public string Note { get; set; }

    public string ImageUrl { get; set; }

    public decimal? HipCircumference { get; set; }

    public virtual Member Member { get; set; }
}