// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Coupon
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public byte DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public decimal MinSpend { get; set; }

    public decimal? MaxDiscount { get; set; }

    public int? TotalQuota { get; set; }

    public int? RemainingQuota { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime EndAt { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? ValidDaysAfterClaim { get; set; }

    public byte? VisibleOnlyOnDayOfMonth { get; set; }

    public string BannerImageUrl { get; set; }

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<ProductOrder> ProductOrders { get; set; } = new List<ProductOrder>();
}