// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Employee
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int DepartmentId { get; set; }

    public int? ManagerId { get; set; }

    public int? WorkDelegateId { get; set; }

    public DateOnly HiredDate { get; set; }

    public bool IsActive { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Employee> InverseManager { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> InverseWorkDelegate { get; set; } = new List<Employee>();

    public virtual ICollection<LeaveApprovalDelegation> LeaveApprovalDelegationDelegateEmployees { get; set; } = new List<LeaveApprovalDelegation>();

    public virtual ICollection<LeaveApprovalDelegation> LeaveApprovalDelegationManagerEmployees { get; set; } = new List<LeaveApprovalDelegation>();

    public virtual ICollection<LeaveBalanceHistory> LeaveBalanceHistories { get; set; } = new List<LeaveBalanceHistory>();

    public virtual ICollection<LeaveBalance> LeaveBalances { get; set; } = new List<LeaveBalance>();

    public virtual ICollection<LeaveRequest> LeaveRequestApprovedByNavigations { get; set; } = new List<LeaveRequest>();

    public virtual ICollection<LeaveRequest> LeaveRequestEmployees { get; set; } = new List<LeaveRequest>();

    public virtual ICollection<LeaveRequest> LeaveRequestLeaveDelegates { get; set; } = new List<LeaveRequest>();

    public virtual Employee Manager { get; set; }

    public virtual User User { get; set; }

    public virtual Employee WorkDelegate { get; set; }
}