// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Food
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public string FoodName { get; set; }

    public bool IsDeleted { get; set; }

    public virtual FoodCategory Category { get; set; }

    public virtual ICollection<FoodRecord> FoodRecords { get; set; } = new List<FoodRecord>();

    public virtual ICollection<Nutrient> Nutrients { get; set; } = new List<Nutrient>();
}