// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class FoodRecord
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateTime EatDT { get; set; }

    public string MealType { get; set; }

    public int FoodId { get; set; }

    public double Amount { get; set; }

    public string Measure { get; set; }

    public virtual Food Food { get; set; }

    public virtual Member Member { get; set; }
}