// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Food
{
    public int Id { get; set; }

    public int CategoryId { get; set; }

    public string FoodName { get; set; }

    public bool IsActive { get; set; }

    public int? MemberId { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual FoodCategory Category { get; set; }

    public virtual ICollection<MemberFavoriteFood> MemberFavoriteFoods { get; set; } = new List<MemberFavoriteFood>();

    public virtual Member Member { get; set; }

    public virtual ICollection<NutrientReferenceValue> NutrientReferenceValues { get; set; } = new List<NutrientReferenceValue>();
}