// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class FoodCategory
{
    public int Id { get; set; }

    public string CategoryName { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();
}