// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Function
{
    public int Id { get; set; }

    public string FunctionName { get; set; }

    public bool IsActive { get; set; }

    public string Description { get; set; }

    public string Api_path { get; set; }

    public virtual ICollection<RoleFunction> RoleFunctions { get; set; } = new List<RoleFunction>();
}