// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Instructor
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public int HourWage { get; set; }

    public int CancelCount { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<InstructorWallet> InstructorWallets { get; set; } = new List<InstructorWallet>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Shift> Shifts { get; set; } = new List<Shift>();

    public virtual User User { get; set; }
}