// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class InstructorWalletDetail
{
    public int Id { get; set; }

    public int InstructorWalletId { get; set; }

    public string SalaryDate { get; set; }

    public decimal TotalAmount { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Category { get; set; }

    public virtual InstructorWallet InstructorWallet { get; set; }
}