// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class KeyWord
{
    public int Id { get; set; }

    public string Word { get; set; }

    public int Category { get; set; }

    public int Weight { get; set; }
}