// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class LeaveBalanceHistory
{
    public int Id { get; set; }

    public int LeaveBalanceId { get; set; }

    public string ChangeType { get; set; }

    public decimal ChangeDays { get; set; }

    public decimal OldTotalDays { get; set; }

    public decimal NewTotalDays { get; set; }

    public decimal OldUsedDays { get; set; }

    public decimal NewUsedDays { get; set; }

    public string Reason { get; set; }

    public int OperatorId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual LeaveBalance LeaveBalance { get; set; }

    public virtual Employee Operator { get; set; }
}