// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class LeaveAttachment
{
    public int Id { get; set; }

    public int RequestId { get; set; }

    public string FileName { get; set; }

    public string FileUrl { get; set; }

    public DateTime UploadedAt { get; set; }

    public virtual LeaveRequest Request { get; set; }
}