// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class LeaveType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int DaysPerYear { get; set; }

    public bool CarryOver { get; set; }

    public bool RequiresDoc { get; set; }

    public bool IsActive { get; set; }

    public string QuotaType { get; set; }

    public int? WarnThresholdDays { get; set; }

    public virtual ICollection<LeaveBalance> LeaveBalances { get; set; } = new List<LeaveBalance>();

    public virtual ICollection<LeaveRequest> LeaveRequests { get; set; } = new List<LeaveRequest>();
}