// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class MemberViolation
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int WarningCount { get; set; }

    public bool IsSuspended { get; set; }

    public DateTime? LastWarningAt { get; set; }

    public DateTime? SuspendedAt { get; set; }

    public string Reason { get; set; }

    public virtual Member Member { get; set; }
}