// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Member
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public byte? Gender { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public double? StartWeight { get; set; }

    public double? Height { get; set; }

    public string ActivityLevel { get; set; }

    public string HealthPlan { get; set; }

    public double? BMR { get; set; }

    public double? TDEE { get; set; }

    public string ImageUrl { get; set; }

    public int CancelCount { get; set; }

    public double? TargetWeight { get; set; }

    public virtual ICollection<BodyRecord> BodyRecords { get; set; } = new List<BodyRecord>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<DailyDiet> DailyDiets { get; set; } = new List<DailyDiet>();

    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<MemberFavoriteFood> MemberFavoriteFoods { get; set; } = new List<MemberFavoriteFood>();

    public virtual MemberGoal MemberGoal { get; set; }

    public virtual MemberViolation MemberViolation { get; set; }

    public virtual ICollection<PointOrder> PointOrders { get; set; } = new List<PointOrder>();

    public virtual ICollection<ProductOrder> ProductOrders { get; set; } = new List<ProductOrder>();

    public virtual ICollection<ReserveOrder> ReserveOrders { get; set; } = new List<ReserveOrder>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual User User { get; set; }

    public virtual UserWallet UserWallet { get; set; }

    public virtual ICollection<WaterLog> WaterLogs { get; set; } = new List<WaterLog>();
}