// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class MemberFavoriteFood
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int FoodId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Food Food { get; set; }

    public virtual Member Member { get; set; }
}
