// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class MemberCoupon
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int CouponId { get; set; }

    public DateTime ClaimedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public int? OrderId { get; set; }

    public string ClaimYearMonth { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Member Member { get; set; }
}