// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class MemberGoal
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public decimal? TargetWeight { get; set; }

    public decimal? CaloriesGoal { get; set; }

    public decimal? ProteinGoal { get; set; }

    public decimal? CarbGoal { get; set; }

    public decimal? FatGoal { get; set; }

    public decimal? WaterGoal { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Member Member { get; set; }
}