// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class MemberGoal
{
    public int M { get; set; }

    public int MemberId { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int? TotalCalories { get; set; }

    public int? Protein { get; set; }

    public int? Carbs { get; set; }

    public int? Fat { get; set; }

    public int? Water { get; set; }

    public virtual Member Member { get; set; }
}