// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Notification
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int? SenderId { get; set; }

    public string NotifyType { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public bool IsRead { get; set; }

    public int? ReferenceId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Sender { get; set; }

    public virtual User User { get; set; }
}