// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Nutrient
{
    public int Id { get; set; }

    public int FoodId { get; set; }

    public int BaseAmount { get; set; }

    public string Measure { get; set; }

    public double? Kcal { get; set; }

    public double? ProteinGram { get; set; }

    public double? CarbGram { get; set; }

    public double? FatGram { get; set; }

    public virtual Food Food { get; set; }
}