// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class NutrientReferenceValue
{
    public int Id { get; set; }

    public int FoodId { get; set; }

    public string Measure { get; set; }

    public decimal BaseAmount { get; set; }

    public int WeightInGrams { get; set; }

    public decimal? Kcal { get; set; }

    public decimal? ProteinGram { get; set; }

    public decimal? CarbGram { get; set; }

    public decimal? FatGram { get; set; }

    public virtual Food Food { get; set; }
}
