// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class ProductOrder
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateTime CreateAt { get; set; }

    public decimal OriginalAmount { get; set; }

    public decimal DiscountAmount { get; set; }

    public string Receiver { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public int? TaxNumber { get; set; }

    public int Status { get; set; }

    public string Memo { get; set; }

    public decimal? FinalAmount { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<ProductOrderDetail> ProductOrderDetails { get; set; } = new List<ProductOrderDetail>();
}