// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class ReserveOrder
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int ShiftId { get; set; }

    public DateTime CreateAt { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public string Target { get; set; }

    public int? PointCost { get; set; }

    public decimal? Price { get; set; }

    public string Memorandum { get; set; }

    public string GoogleEventId { get; set; }

    public string GuestEmail { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<PointsRecordDetail> PointsRecordDetails { get; set; } = new List<PointsRecordDetail>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Shift Shift { get; set; }
}