// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Review
{
    public int Id { get; set; }

    public int ReserveOrderId { get; set; }

    public int InstructorId { get; set; }

    public int MemberId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsBanned { get; set; }

    public virtual Instructor Instructor { get; set; }

    public virtual Member Member { get; set; }

    public virtual ReserveOrder ReserveOrder { get; set; }
}