// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class Shift
{
    public int Id { get; set; }

    public int InstructorId { get; set; }

    public DateOnly ScheduleDate { get; set; }

    public string TimeSlot { get; set; }

    public bool IsBooked { get; set; }

    public virtual Instructor Instructor { get; set; }

    public virtual ICollection<ReserveOrder> ReserveOrders { get; set; } = new List<ReserveOrder>();
}