// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class TopUpPlan
{
    public int Id { get; set; }

    public string PlanName { get; set; }

    public string ImageUrl { get; set; }

    public decimal Price { get; set; }

    public int Points { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public int SortOrder { get; set; }

    public virtual ICollection<PointOrder> PointOrders { get; set; } = new List<PointOrder>();
}