// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class UserPasswordHistory
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string HashedPassword { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}