// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class User
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string HashedPassword { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public string Mobile { get; set; }

    public bool IsConfirmed { get; set; }

    public bool IsActive { get; set; }

    public string NewMemberConfirmCode { get; set; }

    public DateTime? NewMemberConfirmCodeExpiry { get; set; }

    public string ResetPasswordConfirmCode { get; set; }

    public DateTime? ResetPasswordConfirmCodeExpiry { get; set; }

    public bool? IsResetPasswordConfirmCodeUsed { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual ICollection<Notification> NotificationSenders { get; set; } = new List<Notification>();

    public virtual ICollection<Notification> NotificationUsers { get; set; } = new List<Notification>();

    public virtual ICollection<UserExternalLogin> UserExternalLogins { get; set; } = new List<UserExternalLogin>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}