// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class vw_EmployeeDeptInfo
{
    public string UserName { get; set; }

    public string Role { get; set; }

    public string DepartmentName { get; set; }

    public string ManagerName { get; set; }

    public string WorkDelegateName { get; set; }
}