// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class vw_RoleFunction
{
    public string RoleName { get; set; }

    public string FunctionName { get; set; }
}