// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class vw_UserRoleFunction
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public int FunctionId { get; set; }

    public string FunctionName { get; set; }
}