// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class vw_UserMemberFoodRecord
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Email { get; set; }

    public int MemberId { get; set; }

    public byte? Gender { get; set; }

    public double? Weight { get; set; }

    public double? Height { get; set; }

    public double? BMR { get; set; }

    public double? TDEE { get; set; }

    public int FoodRecordId { get; set; }

    public DateTime EatDT { get; set; }

    public string MealType { get; set; }

    public double Amount { get; set; }

    public string RecordMeasure { get; set; }

    public int FoodId { get; set; }

    public string FoodName { get; set; }

    public string CategoryName { get; set; }

    public int? BaseAmount { get; set; }

    public string NutrientMeasure { get; set; }

    public double? TotalKcal { get; set; }

    public double? TotalProtein { get; set; }

    public double? TotalCarb { get; set; }

    public double? TotalFat { get; set; }
}