// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFitnessCoach_Server.Models.EfModels;

public partial class WaterLog
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public DateOnly LogDate { get; set; }

    public int Amount { get; set; }

    public virtual Member Member { get; set; } = null!;
}
