USE [MyFitnessCoachDb];
GO

DECLARE @MemberIds TABLE (RowID INT IDENTITY(1,1), MemberId INT);
INSERT INTO @MemberIds (MemberId) SELECT Id FROM Members ORDER BY Id;

DECLARE @CurrentRow INT = 1;
DECLARE @MaxRow INT = (SELECT COUNT(*) FROM @MemberIds);
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem1.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 1); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem2.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 2); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem3.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 3); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem4.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 4); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem5.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 5); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem6.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 6); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem7.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 7); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem8.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 8); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem9.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 9); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem10.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 10); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem11.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 11); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem12.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 12); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem13.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 13); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem14.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 14); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem15.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 15); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem16.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 16); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem17.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 17); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem18.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 18); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem19.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 19); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem20.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 20); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem21.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 21); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem22.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 22); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem23.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 23); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem24.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 24); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem25.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 25); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem26.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 26); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem27.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 27); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem28.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 28); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem29.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 29); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem30.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 30); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem31.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 31); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem32.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 32); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem33.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 33); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem34.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 34); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem35.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 35); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem36.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 36); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem37.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 37); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem38.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 38); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem39.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 39); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem40.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 40); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem41.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 41); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem42.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 42); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem43.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 43); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem44.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 44); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem45.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 45); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem46.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 46); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem47.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 47); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem48.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 48); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem49.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 49); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem50.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 50); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem51.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 51); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem52.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 52); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem53.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 53); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem54.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 54); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem55.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 55); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem56.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 56); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem57.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 57); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem58.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 58); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem59.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 59); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem60.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 60); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem61.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 61); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem62.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 62); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem63.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 63); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem64.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 64); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem65.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 65); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem66.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 66); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem67.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 67); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem68.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 68); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem69.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 69); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem70.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 70); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem71.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 71); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem72.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 72); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem73.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 73); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem74.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 74); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem75.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 75); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem76.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 76); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem77.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 77); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem78.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 78); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem79.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 79); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem80.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 80); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem81.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 81); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem82.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 82); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem83.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 83); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem84.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 84); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem85.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 85); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem86.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 86); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem87.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 87); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem88.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 88); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem89.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 89); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem90.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 90); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem91.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 91); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem92.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 92); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem93.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 93); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem94.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 94); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem95.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 95); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem96.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 96); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem97.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 97); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem98.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 98); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem99.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 99); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem100.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 100); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem101.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 101); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem102.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 102); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem103.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 103); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem104.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 104); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem105.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 105); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem106.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 106); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem107.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 107); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem108.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 108); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem109.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 109); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem110.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 110); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem111.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 111); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem112.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 112); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem113.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 113); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem114.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 114); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem115.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 115); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem116.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 116); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem117.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 117); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem118.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 118); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem119.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 119); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem120.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 120); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem121.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 121); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem122.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 122); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem123.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 123); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem124.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 124); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem125.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 125); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem126.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 126); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem127.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 127); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem128.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 128); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem129.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 129); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem130.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 130); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem131.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 131); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem132.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 132); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem133.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 133); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem134.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 134); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem135.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 135); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem136.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 136); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem137.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 137); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem138.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 138); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem139.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 139); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem140.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 140); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem141.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 141); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem142.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 142); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem143.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 143); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem144.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 144); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem145.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 145); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem146.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 146); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem147.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 147); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem148.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 148); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem149.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 149); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem150.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 150); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem151.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 151); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem152.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 152); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem153.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 153); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem154.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 154); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem155.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 155); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem156.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 156); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem157.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 157); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem158.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 158); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem159.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 159); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem160.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 160); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem161.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 161); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem162.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 162); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem163.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 163); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem164.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 164); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem165.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 165); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem166.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 166); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem167.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 167); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem168.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 168); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem169.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 169); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem170.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 170); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem171.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 171); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem172.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 172); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem173.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 173); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem174.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 174); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem175.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 175); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem176.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 176); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem177.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 177); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem178.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 178); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem179.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 179); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem180.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 180); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem181.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 181); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem182.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 182); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem183.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 183); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem184.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 184); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem185.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 185); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem186.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 186); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem187.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 187); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem188.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 188); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem189.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 189); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem190.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 190); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem191.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 191); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem192.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 192); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem193.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 193); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem194.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 194); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem195.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 195); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem196.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 196); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem197.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 197); SET @CurrentRow = @CurrentRow + 1; END
IF @CurrentRow <= @MaxRow BEGIN UPDATE Members SET ImageUrl = '/img/members/mem198.jpg' WHERE Id = (SELECT MemberId FROM @MemberIds WHERE RowID = 198); SET @CurrentRow = @CurrentRow + 1; END

PRINT 'Update complete: ' + CAST((CASE WHEN @CurrentRow-1 > @MaxRow THEN @MaxRow ELSE @CurrentRow-1 END) AS VARCHAR) + ' members updated.';
GO
